[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.11"
prost = "0.12"
log = "0.4"
env_logger = "0.10"
age = "0.9"
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.11"
